# Generated by Django 5.0.6 on 2024-07-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="regular_price",
            field=models.PositiveIntegerField(default=10000, verbose_name="정가"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="sale_price",
            field=models.PositiveIntegerField(default=10000, verbose_name="판매가"),
            preserve_default=False,
        ),
    ]
