# Generated by Django 5.0.6 on 2024-07-23 06:47

from django.db import migrations
from event.models import EventType


def create_default_events(apps, schema_editor):
    db = schema_editor.connection.alias
    event = apps.get_model(app_label='event', model_name='Event')
    event.objects.using(db).create(
        title="test1",
        subtitle="test subtitle",
        type=EventType.CONCERT
    )
    event.objects.using(db).create(
        title="test2",
        subtitle="test subtitle",
        type=EventType.SPORTS
    )
    event.objects.using(db).create(
        title="test3",
        subtitle="test subtitle",
        type=EventType.ETC
    )


def reverse_default_events(apps, schema_editor):
    db = schema_editor.connection.alias
    event = apps.get_model(app_label='event', model_name='Event')
    event.objects.using(db).filter(subtitle="test subtitle").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_ticket_regular_price_ticket_sale_price"),
    ]

    operations = [
        migrations.RunPython(code=create_default_events, reverse_code=reverse_default_events)
    ]
